version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name : starter-app
    restart : unless-stopped
    volumes : 
      - ./:/var/www
    networks:
      - testnet
      
  nginx:
    image: nginx:alpine
    container_name: starter-nginx
    restart : unless-stopped
    ports:
      - 7001:80
    volumes :
      - ./:/var/fixed
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
    name: kates